version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.3.1-java11
    environment:
      - CLUSTER_NAME=hadoop
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "9000:9000"

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.3.1-java11
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    volumes:
      - ./hdfs/datanode:/hadoop/dfs/data
    depends_on:
      - hdfs-namenode

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  kafka-producer:
    image: minhhaitknavn/yelp-kafka-producer:2.0.0
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    command: ["python", "producer.py"]

  spark:
    image: minhhaitknavn/yelp-sentiment:2.0.0
    environment:
      - HDFS_URL=hdfs://hdfs-namenode:9000
      - MONGO_URL=mongodb://mongo:27017
      - ELASTIC_URL=http://elasticsearch:9200
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
      - hdfs-namenode
      - mongo
      - elasticsearch
    command: ["python", "Spark/main.py"]
